-- OBSOLÈTE : ne pas exécuter.
-- Le mois comptable = mois de réception / paiement (created_at), pas la date sur la facture.
-- Pour corriger des données déjà basculées sur la date facture, utiliser fix_accounting_month.sql
